// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/osac-project/fulfillment-service/internal/idp (interfaces: Client)
//
// Generated by this command:
//
//	mockgen -destination=client_mock.go -package=idp . Client
//

// Package idp is a generated GoMock package.
package idp

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// AddUserToGroup mocks base method.
func (m *MockClient) AddUserToGroup(ctx context.Context, tenantName, username, groupID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddUserToGroup", ctx, tenantName, username, groupID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddUserToGroup indicates an expected call of AddUserToGroup.
func (mr *MockClientMockRecorder) AddUserToGroup(ctx, tenantName, username, groupID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddUserToGroup", reflect.TypeOf((*MockClient)(nil).AddUserToGroup), ctx, tenantName, username, groupID)
}

// AssignClientRolesToUser mocks base method.
func (m *MockClient) AssignClientRolesToUser(ctx context.Context, tenantName, idpUserID, clientID string, roles []*Role) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignClientRolesToUser", ctx, tenantName, idpUserID, clientID, roles)
	ret0, _ := ret[0].(error)
	return ret0
}

// AssignClientRolesToUser indicates an expected call of AssignClientRolesToUser.
func (mr *MockClientMockRecorder) AssignClientRolesToUser(ctx, tenantName, idpUserID, clientID, roles any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignClientRolesToUser", reflect.TypeOf((*MockClient)(nil).AssignClientRolesToUser), ctx, tenantName, idpUserID, clientID, roles)
}

// AssignIdpManagerPermissions mocks base method.
func (m *MockClient) AssignIdpManagerPermissions(ctx context.Context, idpUserID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignIdpManagerPermissions", ctx, idpUserID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AssignIdpManagerPermissions indicates an expected call of AssignIdpManagerPermissions.
func (mr *MockClientMockRecorder) AssignIdpManagerPermissions(ctx, idpUserID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignIdpManagerPermissions", reflect.TypeOf((*MockClient)(nil).AssignIdpManagerPermissions), ctx, idpUserID)
}

// AssignTenantAdminPermissions mocks base method.
func (m *MockClient) AssignTenantAdminPermissions(ctx context.Context, tenantName, idpUserID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignTenantAdminPermissions", ctx, tenantName, idpUserID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AssignTenantAdminPermissions indicates an expected call of AssignTenantAdminPermissions.
func (mr *MockClientMockRecorder) AssignTenantAdminPermissions(ctx, tenantName, idpUserID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignTenantAdminPermissions", reflect.TypeOf((*MockClient)(nil).AssignTenantAdminPermissions), ctx, tenantName, idpUserID)
}

// AssignTenantRolesToUser mocks base method.
func (m *MockClient) AssignTenantRolesToUser(ctx context.Context, tenantName, idpUserID string, roles []*Role) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignTenantRolesToUser", ctx, tenantName, idpUserID, roles)
	ret0, _ := ret[0].(error)
	return ret0
}

// AssignTenantRolesToUser indicates an expected call of AssignTenantRolesToUser.
func (mr *MockClientMockRecorder) AssignTenantRolesToUser(ctx, tenantName, idpUserID, roles any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignTenantRolesToUser", reflect.TypeOf((*MockClient)(nil).AssignTenantRolesToUser), ctx, tenantName, idpUserID, roles)
}

// CreateAuthorizationGroup mocks base method.
func (m *MockClient) CreateAuthorizationGroup(ctx context.Context, tenantName, groupPath string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAuthorizationGroup", ctx, tenantName, groupPath)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAuthorizationGroup indicates an expected call of CreateAuthorizationGroup.
func (mr *MockClientMockRecorder) CreateAuthorizationGroup(ctx, tenantName, groupPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAuthorizationGroup", reflect.TypeOf((*MockClient)(nil).CreateAuthorizationGroup), ctx, tenantName, groupPath)
}

// CreateAuthorizationResource mocks base method.
func (m *MockClient) CreateAuthorizationResource(ctx context.Context, resource *AuthorizationResource) (*AuthorizationResource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAuthorizationResource", ctx, resource)
	ret0, _ := ret[0].(*AuthorizationResource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAuthorizationResource indicates an expected call of CreateAuthorizationResource.
func (mr *MockClientMockRecorder) CreateAuthorizationResource(ctx, resource any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAuthorizationResource", reflect.TypeOf((*MockClient)(nil).CreateAuthorizationResource), ctx, resource)
}

// CreateIdentityProvider mocks base method.
func (m *MockClient) CreateIdentityProvider(ctx context.Context, tenantName string, idp *IdentityProvider) (*IdentityProvider, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateIdentityProvider", ctx, tenantName, idp)
	ret0, _ := ret[0].(*IdentityProvider)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateIdentityProvider indicates an expected call of CreateIdentityProvider.
func (mr *MockClientMockRecorder) CreateIdentityProvider(ctx, tenantName, idp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateIdentityProvider", reflect.TypeOf((*MockClient)(nil).CreateIdentityProvider), ctx, tenantName, idp)
}

// CreateTenant mocks base method.
func (m *MockClient) CreateTenant(ctx context.Context, tenant *Tenant) (*Tenant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTenant", ctx, tenant)
	ret0, _ := ret[0].(*Tenant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTenant indicates an expected call of CreateTenant.
func (mr *MockClientMockRecorder) CreateTenant(ctx, tenant any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTenant", reflect.TypeOf((*MockClient)(nil).CreateTenant), ctx, tenant)
}

// CreateUser mocks base method.
func (m *MockClient) CreateUser(ctx context.Context, tenantName string, user *User) (*User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, tenantName, user)
	ret0, _ := ret[0].(*User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockClientMockRecorder) CreateUser(ctx, tenantName, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockClient)(nil).CreateUser), ctx, tenantName, user)
}

// DeleteAuthorizationGroup mocks base method.
func (m *MockClient) DeleteAuthorizationGroup(ctx context.Context, tenantName, groupID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAuthorizationGroup", ctx, tenantName, groupID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAuthorizationGroup indicates an expected call of DeleteAuthorizationGroup.
func (mr *MockClientMockRecorder) DeleteAuthorizationGroup(ctx, tenantName, groupID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAuthorizationGroup", reflect.TypeOf((*MockClient)(nil).DeleteAuthorizationGroup), ctx, tenantName, groupID)
}

// DeleteAuthorizationResource mocks base method.
func (m *MockClient) DeleteAuthorizationResource(ctx context.Context, resourceID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAuthorizationResource", ctx, resourceID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAuthorizationResource indicates an expected call of DeleteAuthorizationResource.
func (mr *MockClientMockRecorder) DeleteAuthorizationResource(ctx, resourceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAuthorizationResource", reflect.TypeOf((*MockClient)(nil).DeleteAuthorizationResource), ctx, resourceID)
}

// DeleteIdentityProvider mocks base method.
func (m *MockClient) DeleteIdentityProvider(ctx context.Context, tenantName, alias string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteIdentityProvider", ctx, tenantName, alias)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteIdentityProvider indicates an expected call of DeleteIdentityProvider.
func (mr *MockClientMockRecorder) DeleteIdentityProvider(ctx, tenantName, alias any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteIdentityProvider", reflect.TypeOf((*MockClient)(nil).DeleteIdentityProvider), ctx, tenantName, alias)
}

// DeleteTenant mocks base method.
func (m *MockClient) DeleteTenant(ctx context.Context, tenantName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTenant", ctx, tenantName)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTenant indicates an expected call of DeleteTenant.
func (mr *MockClientMockRecorder) DeleteTenant(ctx, tenantName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTenant", reflect.TypeOf((*MockClient)(nil).DeleteTenant), ctx, tenantName)
}

// DeleteUser mocks base method.
func (m *MockClient) DeleteUser(ctx context.Context, tenantName, idpUserID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUser", ctx, tenantName, idpUserID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUser indicates an expected call of DeleteUser.
func (mr *MockClientMockRecorder) DeleteUser(ctx, tenantName, idpUserID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUser", reflect.TypeOf((*MockClient)(nil).DeleteUser), ctx, tenantName, idpUserID)
}

// GetAuthorizationResource mocks base method.
func (m *MockClient) GetAuthorizationResource(ctx context.Context, resourceID string) (*AuthorizationResource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAuthorizationResource", ctx, resourceID)
	ret0, _ := ret[0].(*AuthorizationResource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAuthorizationResource indicates an expected call of GetAuthorizationResource.
func (mr *MockClientMockRecorder) GetAuthorizationResource(ctx, resourceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAuthorizationResource", reflect.TypeOf((*MockClient)(nil).GetAuthorizationResource), ctx, resourceID)
}

// GetGroupIDByPath mocks base method.
func (m *MockClient) GetGroupIDByPath(ctx context.Context, tenantName, groupPath string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGroupIDByPath", ctx, tenantName, groupPath)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGroupIDByPath indicates an expected call of GetGroupIDByPath.
func (mr *MockClientMockRecorder) GetGroupIDByPath(ctx, tenantName, groupPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGroupIDByPath", reflect.TypeOf((*MockClient)(nil).GetGroupIDByPath), ctx, tenantName, groupPath)
}

// GetIdentityProvider mocks base method.
func (m *MockClient) GetIdentityProvider(ctx context.Context, tenantName, alias string) (*IdentityProvider, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIdentityProvider", ctx, tenantName, alias)
	ret0, _ := ret[0].(*IdentityProvider)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIdentityProvider indicates an expected call of GetIdentityProvider.
func (mr *MockClientMockRecorder) GetIdentityProvider(ctx, tenantName, alias any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIdentityProvider", reflect.TypeOf((*MockClient)(nil).GetIdentityProvider), ctx, tenantName, alias)
}

// GetTenant mocks base method.
func (m *MockClient) GetTenant(ctx context.Context, name string) (*Tenant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTenant", ctx, name)
	ret0, _ := ret[0].(*Tenant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTenant indicates an expected call of GetTenant.
func (mr *MockClientMockRecorder) GetTenant(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTenant", reflect.TypeOf((*MockClient)(nil).GetTenant), ctx, name)
}

// GetUser mocks base method.
func (m *MockClient) GetUser(ctx context.Context, tenantName, idpUserID string) (*User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser", ctx, tenantName, idpUserID)
	ret0, _ := ret[0].(*User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUser indicates an expected call of GetUser.
func (mr *MockClientMockRecorder) GetUser(ctx, tenantName, idpUserID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockClient)(nil).GetUser), ctx, tenantName, idpUserID)
}

// GetUserByUsername mocks base method.
func (m *MockClient) GetUserByUsername(ctx context.Context, tenantName, username string) (*User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByUsername", ctx, tenantName, username)
	ret0, _ := ret[0].(*User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByUsername indicates an expected call of GetUserByUsername.
func (mr *MockClientMockRecorder) GetUserByUsername(ctx, tenantName, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByUsername", reflect.TypeOf((*MockClient)(nil).GetUserByUsername), ctx, tenantName, username)
}

// GetUserClientRoles mocks base method.
func (m *MockClient) GetUserClientRoles(ctx context.Context, tenantName, idpUserID, clientID string) ([]*Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserClientRoles", ctx, tenantName, idpUserID, clientID)
	ret0, _ := ret[0].([]*Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserClientRoles indicates an expected call of GetUserClientRoles.
func (mr *MockClientMockRecorder) GetUserClientRoles(ctx, tenantName, idpUserID, clientID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserClientRoles", reflect.TypeOf((*MockClient)(nil).GetUserClientRoles), ctx, tenantName, idpUserID, clientID)
}

// GetUserTenantRoles mocks base method.
func (m *MockClient) GetUserTenantRoles(ctx context.Context, tenantName, idpUserID string) ([]*Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserTenantRoles", ctx, tenantName, idpUserID)
	ret0, _ := ret[0].([]*Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserTenantRoles indicates an expected call of GetUserTenantRoles.
func (mr *MockClientMockRecorder) GetUserTenantRoles(ctx, tenantName, idpUserID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserTenantRoles", reflect.TypeOf((*MockClient)(nil).GetUserTenantRoles), ctx, tenantName, idpUserID)
}

// ListClientRoles mocks base method.
func (m *MockClient) ListClientRoles(ctx context.Context, tenantName, clientID string) ([]*Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListClientRoles", ctx, tenantName, clientID)
	ret0, _ := ret[0].([]*Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListClientRoles indicates an expected call of ListClientRoles.
func (mr *MockClientMockRecorder) ListClientRoles(ctx, tenantName, clientID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListClientRoles", reflect.TypeOf((*MockClient)(nil).ListClientRoles), ctx, tenantName, clientID)
}

// ListIdentityProviders mocks base method.
func (m *MockClient) ListIdentityProviders(ctx context.Context, tenantName string) ([]*IdentityProvider, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListIdentityProviders", ctx, tenantName)
	ret0, _ := ret[0].([]*IdentityProvider)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListIdentityProviders indicates an expected call of ListIdentityProviders.
func (mr *MockClientMockRecorder) ListIdentityProviders(ctx, tenantName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListIdentityProviders", reflect.TypeOf((*MockClient)(nil).ListIdentityProviders), ctx, tenantName)
}

// ListTenantRoles mocks base method.
func (m *MockClient) ListTenantRoles(ctx context.Context, tenantName string) ([]*Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTenantRoles", ctx, tenantName)
	ret0, _ := ret[0].([]*Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTenantRoles indicates an expected call of ListTenantRoles.
func (mr *MockClientMockRecorder) ListTenantRoles(ctx, tenantName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTenantRoles", reflect.TypeOf((*MockClient)(nil).ListTenantRoles), ctx, tenantName)
}

// ListUsers mocks base method.
func (m *MockClient) ListUsers(ctx context.Context, tenantName string) ([]*User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUsers", ctx, tenantName)
	ret0, _ := ret[0].([]*User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUsers indicates an expected call of ListUsers.
func (mr *MockClientMockRecorder) ListUsers(ctx, tenantName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUsers", reflect.TypeOf((*MockClient)(nil).ListUsers), ctx, tenantName)
}

// RemoveClientRolesFromUser mocks base method.
func (m *MockClient) RemoveClientRolesFromUser(ctx context.Context, tenantName, idpUserID, clientID string, roles []*Role) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveClientRolesFromUser", ctx, tenantName, idpUserID, clientID, roles)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveClientRolesFromUser indicates an expected call of RemoveClientRolesFromUser.
func (mr *MockClientMockRecorder) RemoveClientRolesFromUser(ctx, tenantName, idpUserID, clientID, roles any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveClientRolesFromUser", reflect.TypeOf((*MockClient)(nil).RemoveClientRolesFromUser), ctx, tenantName, idpUserID, clientID, roles)
}

// RemoveTenantRolesFromUser mocks base method.
func (m *MockClient) RemoveTenantRolesFromUser(ctx context.Context, tenantName, idpUserID string, roles []*Role) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveTenantRolesFromUser", ctx, tenantName, idpUserID, roles)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveTenantRolesFromUser indicates an expected call of RemoveTenantRolesFromUser.
func (mr *MockClientMockRecorder) RemoveTenantRolesFromUser(ctx, tenantName, idpUserID, roles any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveTenantRolesFromUser", reflect.TypeOf((*MockClient)(nil).RemoveTenantRolesFromUser), ctx, tenantName, idpUserID, roles)
}

// RemoveUserFromGroup mocks base method.
func (m *MockClient) RemoveUserFromGroup(ctx context.Context, tenantName, username, groupID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveUserFromGroup", ctx, tenantName, username, groupID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveUserFromGroup indicates an expected call of RemoveUserFromGroup.
func (mr *MockClientMockRecorder) RemoveUserFromGroup(ctx, tenantName, username, groupID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveUserFromGroup", reflect.TypeOf((*MockClient)(nil).RemoveUserFromGroup), ctx, tenantName, username, groupID)
}

// UpdateTenant mocks base method.
func (m *MockClient) UpdateTenant(ctx context.Context, tenant *Tenant) (*Tenant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTenant", ctx, tenant)
	ret0, _ := ret[0].(*Tenant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTenant indicates an expected call of UpdateTenant.
func (mr *MockClientMockRecorder) UpdateTenant(ctx, tenant any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTenant", reflect.TypeOf((*MockClient)(nil).UpdateTenant), ctx, tenant)
}
