repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
    - id: trailing-whitespace
    - id: check-merge-conflict
    - id: end-of-file-fixer
    - id: check-added-large-files
    - id: check-case-conflict
    - id: check-json
    - id: check-symlinks
    - id: detect-private-key

- repo: https://github.com/adrienverge/yamllint.git
  rev: v1.35.1
  hooks:
    - id: yamllint
      files: \.(yaml|yml)$
      types: [file, yaml]
      entry: yamllint --strict
      exclude: ^(charts|it/charts)/.*/templates/

- repo: local
  hooks:
  - id: golangci-lint
    pass_filenames: false
    name: golangci-lint
    language: system
    files: \.go$
    entry: uv run dev.py lint go
  - id: buf-lint
    pass_filenames: false
    name: buf-lint
    language: system
    files: \.proto$
    entry: uv run dev.py lint proto
