// Code generated by MockGen. DO NOT EDIT.
// Source: ../../api/osac/private/v1/external_ip_pools_service_grpc.pb.go
//
// Generated by this command:
//
//	mockgen -source=../../api/osac/private/v1/external_ip_pools_service_grpc.pb.go -destination=external_ip_pools_client_mock.go -package=externalippool ExternalIPPoolsClient
//

// Package externalippool is a generated GoMock package.
package externalippool

import (
	context "context"
	reflect "reflect"

	privatev1 "github.com/osac-project/fulfillment-service/internal/api/osac/private/v1"
	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockExternalIPPoolsClient is a mock of ExternalIPPoolsClient interface.
type MockExternalIPPoolsClient struct {
	ctrl     *gomock.Controller
	recorder *MockExternalIPPoolsClientMockRecorder
	isgomock struct{}
}

// MockExternalIPPoolsClientMockRecorder is the mock recorder for MockExternalIPPoolsClient.
type MockExternalIPPoolsClientMockRecorder struct {
	mock *MockExternalIPPoolsClient
}

// NewMockExternalIPPoolsClient creates a new mock instance.
func NewMockExternalIPPoolsClient(ctrl *gomock.Controller) *MockExternalIPPoolsClient {
	mock := &MockExternalIPPoolsClient{ctrl: ctrl}
	mock.recorder = &MockExternalIPPoolsClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExternalIPPoolsClient) EXPECT() *MockExternalIPPoolsClientMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockExternalIPPoolsClient) Create(ctx context.Context, in *privatev1.ExternalIPPoolsCreateRequest, opts ...grpc.CallOption) (*privatev1.ExternalIPPoolsCreateResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Create", varargs...)
	ret0, _ := ret[0].(*privatev1.ExternalIPPoolsCreateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockExternalIPPoolsClientMockRecorder) Create(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockExternalIPPoolsClient)(nil).Create), varargs...)
}

// Delete mocks base method.
func (m *MockExternalIPPoolsClient) Delete(ctx context.Context, in *privatev1.ExternalIPPoolsDeleteRequest, opts ...grpc.CallOption) (*privatev1.ExternalIPPoolsDeleteResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Delete", varargs...)
	ret0, _ := ret[0].(*privatev1.ExternalIPPoolsDeleteResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockExternalIPPoolsClientMockRecorder) Delete(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockExternalIPPoolsClient)(nil).Delete), varargs...)
}

// Get mocks base method.
func (m *MockExternalIPPoolsClient) Get(ctx context.Context, in *privatev1.ExternalIPPoolsGetRequest, opts ...grpc.CallOption) (*privatev1.ExternalIPPoolsGetResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Get", varargs...)
	ret0, _ := ret[0].(*privatev1.ExternalIPPoolsGetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockExternalIPPoolsClientMockRecorder) Get(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockExternalIPPoolsClient)(nil).Get), varargs...)
}

// List mocks base method.
func (m *MockExternalIPPoolsClient) List(ctx context.Context, in *privatev1.ExternalIPPoolsListRequest, opts ...grpc.CallOption) (*privatev1.ExternalIPPoolsListResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "List", varargs...)
	ret0, _ := ret[0].(*privatev1.ExternalIPPoolsListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockExternalIPPoolsClientMockRecorder) List(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockExternalIPPoolsClient)(nil).List), varargs...)
}

// Signal mocks base method.
func (m *MockExternalIPPoolsClient) Signal(ctx context.Context, in *privatev1.ExternalIPPoolsSignalRequest, opts ...grpc.CallOption) (*privatev1.ExternalIPPoolsSignalResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Signal", varargs...)
	ret0, _ := ret[0].(*privatev1.ExternalIPPoolsSignalResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Signal indicates an expected call of Signal.
func (mr *MockExternalIPPoolsClientMockRecorder) Signal(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Signal", reflect.TypeOf((*MockExternalIPPoolsClient)(nil).Signal), varargs...)
}

// Update mocks base method.
func (m *MockExternalIPPoolsClient) Update(ctx context.Context, in *privatev1.ExternalIPPoolsUpdateRequest, opts ...grpc.CallOption) (*privatev1.ExternalIPPoolsUpdateResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Update", varargs...)
	ret0, _ := ret[0].(*privatev1.ExternalIPPoolsUpdateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockExternalIPPoolsClientMockRecorder) Update(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockExternalIPPoolsClient)(nil).Update), varargs...)
}

// MockExternalIPPoolsServer is a mock of ExternalIPPoolsServer interface.
type MockExternalIPPoolsServer struct {
	ctrl     *gomock.Controller
	recorder *MockExternalIPPoolsServerMockRecorder
	isgomock struct{}
}

// MockExternalIPPoolsServerMockRecorder is the mock recorder for MockExternalIPPoolsServer.
type MockExternalIPPoolsServerMockRecorder struct {
	mock *MockExternalIPPoolsServer
}

// NewMockExternalIPPoolsServer creates a new mock instance.
func NewMockExternalIPPoolsServer(ctrl *gomock.Controller) *MockExternalIPPoolsServer {
	mock := &MockExternalIPPoolsServer{ctrl: ctrl}
	mock.recorder = &MockExternalIPPoolsServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExternalIPPoolsServer) EXPECT() *MockExternalIPPoolsServerMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockExternalIPPoolsServer) Create(arg0 context.Context, arg1 *privatev1.ExternalIPPoolsCreateRequest) (*privatev1.ExternalIPPoolsCreateResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(*privatev1.ExternalIPPoolsCreateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockExternalIPPoolsServerMockRecorder) Create(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockExternalIPPoolsServer)(nil).Create), arg0, arg1)
}

// Delete mocks base method.
func (m *MockExternalIPPoolsServer) Delete(arg0 context.Context, arg1 *privatev1.ExternalIPPoolsDeleteRequest) (*privatev1.ExternalIPPoolsDeleteResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(*privatev1.ExternalIPPoolsDeleteResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockExternalIPPoolsServerMockRecorder) Delete(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockExternalIPPoolsServer)(nil).Delete), arg0, arg1)
}

// Get mocks base method.
func (m *MockExternalIPPoolsServer) Get(arg0 context.Context, arg1 *privatev1.ExternalIPPoolsGetRequest) (*privatev1.ExternalIPPoolsGetResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(*privatev1.ExternalIPPoolsGetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockExternalIPPoolsServerMockRecorder) Get(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockExternalIPPoolsServer)(nil).Get), arg0, arg1)
}

// List mocks base method.
func (m *MockExternalIPPoolsServer) List(arg0 context.Context, arg1 *privatev1.ExternalIPPoolsListRequest) (*privatev1.ExternalIPPoolsListResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1)
	ret0, _ := ret[0].(*privatev1.ExternalIPPoolsListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockExternalIPPoolsServerMockRecorder) List(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockExternalIPPoolsServer)(nil).List), arg0, arg1)
}

// Signal mocks base method.
func (m *MockExternalIPPoolsServer) Signal(arg0 context.Context, arg1 *privatev1.ExternalIPPoolsSignalRequest) (*privatev1.ExternalIPPoolsSignalResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Signal", arg0, arg1)
	ret0, _ := ret[0].(*privatev1.ExternalIPPoolsSignalResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Signal indicates an expected call of Signal.
func (mr *MockExternalIPPoolsServerMockRecorder) Signal(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Signal", reflect.TypeOf((*MockExternalIPPoolsServer)(nil).Signal), arg0, arg1)
}

// Update mocks base method.
func (m *MockExternalIPPoolsServer) Update(arg0 context.Context, arg1 *privatev1.ExternalIPPoolsUpdateRequest) (*privatev1.ExternalIPPoolsUpdateResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(*privatev1.ExternalIPPoolsUpdateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockExternalIPPoolsServerMockRecorder) Update(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockExternalIPPoolsServer)(nil).Update), arg0, arg1)
}

// mustEmbedUnimplementedExternalIPPoolsServer mocks base method.
func (m *MockExternalIPPoolsServer) mustEmbedUnimplementedExternalIPPoolsServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedExternalIPPoolsServer")
}

// mustEmbedUnimplementedExternalIPPoolsServer indicates an expected call of mustEmbedUnimplementedExternalIPPoolsServer.
func (mr *MockExternalIPPoolsServerMockRecorder) mustEmbedUnimplementedExternalIPPoolsServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedExternalIPPoolsServer", reflect.TypeOf((*MockExternalIPPoolsServer)(nil).mustEmbedUnimplementedExternalIPPoolsServer))
}

// MockUnsafeExternalIPPoolsServer is a mock of UnsafeExternalIPPoolsServer interface.
type MockUnsafeExternalIPPoolsServer struct {
	ctrl     *gomock.Controller
	recorder *MockUnsafeExternalIPPoolsServerMockRecorder
	isgomock struct{}
}

// MockUnsafeExternalIPPoolsServerMockRecorder is the mock recorder for MockUnsafeExternalIPPoolsServer.
type MockUnsafeExternalIPPoolsServerMockRecorder struct {
	mock *MockUnsafeExternalIPPoolsServer
}

// NewMockUnsafeExternalIPPoolsServer creates a new mock instance.
func NewMockUnsafeExternalIPPoolsServer(ctrl *gomock.Controller) *MockUnsafeExternalIPPoolsServer {
	mock := &MockUnsafeExternalIPPoolsServer{ctrl: ctrl}
	mock.recorder = &MockUnsafeExternalIPPoolsServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUnsafeExternalIPPoolsServer) EXPECT() *MockUnsafeExternalIPPoolsServerMockRecorder {
	return m.recorder
}

// mustEmbedUnimplementedExternalIPPoolsServer mocks base method.
func (m *MockUnsafeExternalIPPoolsServer) mustEmbedUnimplementedExternalIPPoolsServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedExternalIPPoolsServer")
}

// mustEmbedUnimplementedExternalIPPoolsServer indicates an expected call of mustEmbedUnimplementedExternalIPPoolsServer.
func (mr *MockUnsafeExternalIPPoolsServerMockRecorder) mustEmbedUnimplementedExternalIPPoolsServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedExternalIPPoolsServer", reflect.TypeOf((*MockUnsafeExternalIPPoolsServer)(nil).mustEmbedUnimplementedExternalIPPoolsServer))
}
