#
# Copyright (c) 2025 Red Hat Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
# the License. You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
# specific language governing permissions and limitations under the License.
#

apiVersion: apps/v1
kind: Deployment
metadata:
  name: fulfillment-grpc-server
spec:
  selector:
    matchLabels:
      app: fulfillment-grpc-server
  replicas: 1
  template:
    metadata:
      labels:
        app: fulfillment-grpc-server
    spec:
      volumes:
      - name: cas
        configMap:
          name: ca-bundle
      - name: cert
        secret:
          secretName: fulfillment-database-client-cert
      - name: tls
        secret:
          secretName: fulfillment-grpc-server-tls
      - name: token-signer
        secret:
          secretName: fulfillment-token-signer-keypair
      - name: token-encryption-cert
        secret:
          secretName: fulfillment-token-encryption-keypair
          items:
          - key: tls.crt
            path: tls.crt
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: grpc-server
        image: fulfillment-service
        imagePullPolicy: IfNotPresent
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - name: cas
          mountPath: /etc/fulfillment-grpc-server/tls/cas
        - name: cert
          mountPath: /secrets/cert
        - name: tls
          mountPath: /etc/fulfillment-grpc-server/tls
        - name: token-signer
          mountPath: /etc/fulfillment-token-signer
          readOnly: true
        - name: token-encryption-cert
          mountPath: /etc/fulfillment-token-encryption
          readOnly: true
        command:
        - /usr/local/bin/fulfillment-service
        - start
        - grpc-server
        - --log-level=info
        - --log-headers=false
        - --log-bodies=false
        - --ca-file=/etc/fulfillment-grpc-server/tls/cas
        - "--db-url=postgres://client@fulfillment-database:5432/service?\
          sslmode=verify-full&\
          sslcert=/secrets/cert/tls.crt&\
          sslkey=/secrets/cert/tls.key&\
          sslrootcert=/secrets/cert/ca.crt"
        - --grpc-listener-address=0.0.0.0:8000
        - --grpc-listener-tls-crt=/etc/fulfillment-grpc-server/tls/tls.crt
        - --grpc-listener-tls-key=/etc/fulfillment-grpc-server/tls/tls.key
        - --grpc-authn-trusted-token-issuers=https://keycloak.keycloak.svc.cluster.local:8000/realms/osac
        - --metrics-listener-address=0.0.0.0:8002
        - --token-signer-crt=/etc/fulfillment-token-signer/tls.crt
        - --token-signer-key=/etc/fulfillment-token-signer/tls.key
        - --token-encryption-crt=/etc/fulfillment-token-encryption/tls.crt
        - --token-issuer=https://fulfillment-api:8000
        ports:
        - name: grpc
          containerPort: 8000
          protocol: TCP
        - name: metrics
          containerPort: 8002
          protocol: TCP
        livenessProbe:
          exec:
            command:
            - /usr/local/bin/fulfillment-service
            - probe
            - grpc-server
            - --ca-file=/etc/fulfillment-grpc-server/tls/ca.crt
            - --grpc-server-address=localhost:8000
            - --grpc-server-timeout=1s
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - /usr/local/bin/fulfillment-service
            - probe
            - grpc-server
            - --ca-file=/etc/fulfillment-grpc-server/tls/ca.crt
            - --grpc-server-address=localhost:8000
            - --grpc-server-timeout=1s
          initialDelaySeconds: 5
          periodSeconds: 10
