//
// Copyright (c) 2025 Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: osac/private/v1/cluster_versions_service.proto

package privatev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ClusterVersions_List_FullMethodName   = "/osac.private.v1.ClusterVersions/List"
	ClusterVersions_Get_FullMethodName    = "/osac.private.v1.ClusterVersions/Get"
	ClusterVersions_Create_FullMethodName = "/osac.private.v1.ClusterVersions/Create"
	ClusterVersions_Update_FullMethodName = "/osac.private.v1.ClusterVersions/Update"
	ClusterVersions_Delete_FullMethodName = "/osac.private.v1.ClusterVersions/Delete"
	ClusterVersions_Signal_FullMethodName = "/osac.private.v1.ClusterVersions/Signal"
)

// ClusterVersionsClient is the client API for ClusterVersions service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ClusterVersionsClient interface {
	// Retrieves the list of cluster versions. Returns active and deprecated versions by default.
	List(ctx context.Context, in *ClusterVersionsListRequest, opts ...grpc.CallOption) (*ClusterVersionsListResponse, error)
	// Retrieves the details of one specific cluster version.
	Get(ctx context.Context, in *ClusterVersionsGetRequest, opts ...grpc.CallOption) (*ClusterVersionsGetResponse, error)
	// Registers a new OpenShift version in the catalog. Requires `spec.version` and `spec.image`;
	// `spec.enabled` defaults to true and `spec.state` defaults to ACTIVE.
	Create(ctx context.Context, in *ClusterVersionsCreateRequest, opts ...grpc.CallOption) (*ClusterVersionsCreateResponse, error)
	// Updates a cluster version. Allows modifying lifecycle state, availability, and upgrade constraints. The
	// `spec.version` and `spec.image` fields are immutable.
	Update(ctx context.Context, in *ClusterVersionsUpdateRequest, opts ...grpc.CallOption) (*ClusterVersionsUpdateResponse, error)
	// Removes a cluster version from the catalog. Rejected if the version is referenced by active clusters,
	// templates, or catalog items.
	Delete(ctx context.Context, in *ClusterVersionsDeleteRequest, opts ...grpc.CallOption) (*ClusterVersionsDeleteResponse, error)
	// Indicates that something changed in the object or the system that may require reconciling the object.
	Signal(ctx context.Context, in *ClusterVersionsSignalRequest, opts ...grpc.CallOption) (*ClusterVersionsSignalResponse, error)
}

type clusterVersionsClient struct {
	cc grpc.ClientConnInterface
}

func NewClusterVersionsClient(cc grpc.ClientConnInterface) ClusterVersionsClient {
	return &clusterVersionsClient{cc}
}

func (c *clusterVersionsClient) List(ctx context.Context, in *ClusterVersionsListRequest, opts ...grpc.CallOption) (*ClusterVersionsListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClusterVersionsListResponse)
	err := c.cc.Invoke(ctx, ClusterVersions_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterVersionsClient) Get(ctx context.Context, in *ClusterVersionsGetRequest, opts ...grpc.CallOption) (*ClusterVersionsGetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClusterVersionsGetResponse)
	err := c.cc.Invoke(ctx, ClusterVersions_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterVersionsClient) Create(ctx context.Context, in *ClusterVersionsCreateRequest, opts ...grpc.CallOption) (*ClusterVersionsCreateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClusterVersionsCreateResponse)
	err := c.cc.Invoke(ctx, ClusterVersions_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterVersionsClient) Update(ctx context.Context, in *ClusterVersionsUpdateRequest, opts ...grpc.CallOption) (*ClusterVersionsUpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClusterVersionsUpdateResponse)
	err := c.cc.Invoke(ctx, ClusterVersions_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterVersionsClient) Delete(ctx context.Context, in *ClusterVersionsDeleteRequest, opts ...grpc.CallOption) (*ClusterVersionsDeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClusterVersionsDeleteResponse)
	err := c.cc.Invoke(ctx, ClusterVersions_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterVersionsClient) Signal(ctx context.Context, in *ClusterVersionsSignalRequest, opts ...grpc.CallOption) (*ClusterVersionsSignalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClusterVersionsSignalResponse)
	err := c.cc.Invoke(ctx, ClusterVersions_Signal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClusterVersionsServer is the server API for ClusterVersions service.
// All implementations must embed UnimplementedClusterVersionsServer
// for forward compatibility.
type ClusterVersionsServer interface {
	// Retrieves the list of cluster versions. Returns active and deprecated versions by default.
	List(context.Context, *ClusterVersionsListRequest) (*ClusterVersionsListResponse, error)
	// Retrieves the details of one specific cluster version.
	Get(context.Context, *ClusterVersionsGetRequest) (*ClusterVersionsGetResponse, error)
	// Registers a new OpenShift version in the catalog. Requires `spec.version` and `spec.image`;
	// `spec.enabled` defaults to true and `spec.state` defaults to ACTIVE.
	Create(context.Context, *ClusterVersionsCreateRequest) (*ClusterVersionsCreateResponse, error)
	// Updates a cluster version. Allows modifying lifecycle state, availability, and upgrade constraints. The
	// `spec.version` and `spec.image` fields are immutable.
	Update(context.Context, *ClusterVersionsUpdateRequest) (*ClusterVersionsUpdateResponse, error)
	// Removes a cluster version from the catalog. Rejected if the version is referenced by active clusters,
	// templates, or catalog items.
	Delete(context.Context, *ClusterVersionsDeleteRequest) (*ClusterVersionsDeleteResponse, error)
	// Indicates that something changed in the object or the system that may require reconciling the object.
	Signal(context.Context, *ClusterVersionsSignalRequest) (*ClusterVersionsSignalResponse, error)
	mustEmbedUnimplementedClusterVersionsServer()
}

// UnimplementedClusterVersionsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedClusterVersionsServer struct{}

func (UnimplementedClusterVersionsServer) List(context.Context, *ClusterVersionsListRequest) (*ClusterVersionsListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedClusterVersionsServer) Get(context.Context, *ClusterVersionsGetRequest) (*ClusterVersionsGetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedClusterVersionsServer) Create(context.Context, *ClusterVersionsCreateRequest) (*ClusterVersionsCreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedClusterVersionsServer) Update(context.Context, *ClusterVersionsUpdateRequest) (*ClusterVersionsUpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedClusterVersionsServer) Delete(context.Context, *ClusterVersionsDeleteRequest) (*ClusterVersionsDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedClusterVersionsServer) Signal(context.Context, *ClusterVersionsSignalRequest) (*ClusterVersionsSignalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Signal not implemented")
}
func (UnimplementedClusterVersionsServer) mustEmbedUnimplementedClusterVersionsServer() {}
func (UnimplementedClusterVersionsServer) testEmbeddedByValue()                         {}

// UnsafeClusterVersionsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClusterVersionsServer will
// result in compilation errors.
type UnsafeClusterVersionsServer interface {
	mustEmbedUnimplementedClusterVersionsServer()
}

func RegisterClusterVersionsServer(s grpc.ServiceRegistrar, srv ClusterVersionsServer) {
	// If the following call pancis, it indicates UnimplementedClusterVersionsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ClusterVersions_ServiceDesc, srv)
}

func _ClusterVersions_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClusterVersionsListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterVersionsServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClusterVersions_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterVersionsServer).List(ctx, req.(*ClusterVersionsListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClusterVersions_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClusterVersionsGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterVersionsServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClusterVersions_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterVersionsServer).Get(ctx, req.(*ClusterVersionsGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClusterVersions_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClusterVersionsCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterVersionsServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClusterVersions_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterVersionsServer).Create(ctx, req.(*ClusterVersionsCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClusterVersions_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClusterVersionsUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterVersionsServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClusterVersions_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterVersionsServer).Update(ctx, req.(*ClusterVersionsUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClusterVersions_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClusterVersionsDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterVersionsServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClusterVersions_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterVersionsServer).Delete(ctx, req.(*ClusterVersionsDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClusterVersions_Signal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClusterVersionsSignalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterVersionsServer).Signal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClusterVersions_Signal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterVersionsServer).Signal(ctx, req.(*ClusterVersionsSignalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ClusterVersions_ServiceDesc is the grpc.ServiceDesc for ClusterVersions service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClusterVersions_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "osac.private.v1.ClusterVersions",
	HandlerType: (*ClusterVersionsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _ClusterVersions_List_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _ClusterVersions_Get_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _ClusterVersions_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _ClusterVersions_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _ClusterVersions_Delete_Handler,
		},
		{
			MethodName: "Signal",
			Handler:    _ClusterVersions_Signal_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "osac/private/v1/cluster_versions_service.proto",
}
