//
// Copyright (c) 2025 Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        (unknown)
// source: osac/private/v1/cluster_version_type.proto

//go:build !protoopaque

package privatev1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Lifecycle states for ClusterVersion resources.
//
// All transitions between states are allowed: ACTIVE <-> DEPRECATED <-> OBSOLETE, ACTIVE <-> OBSOLETE.
// Timestamps in ClusterVersionDeprecation are managed automatically during transitions.
type ClusterVersionState int32

const (
	// State is unknown or has not been determined yet.
	ClusterVersionState_CLUSTER_VERSION_STATE_UNSPECIFIED ClusterVersionState = 0
	// The cluster version is fully available for new cluster creation.
	//
	// This is the default state assigned on creation. Returning to ACTIVE from DEPRECATED or OBSOLETE
	// retains the corresponding deprecation timestamps as historical record.
	ClusterVersionState_CLUSTER_VERSION_STATE_ACTIVE ClusterVersionState = 1
	// The cluster version is available with warnings; migration to a newer version is recommended.
	//
	// Clusters can still be created with a deprecated version, but users are encouraged to choose an
	// active version instead. The deprecation_timestamp is set automatically on transition to this state.
	ClusterVersionState_CLUSTER_VERSION_STATE_DEPRECATED ClusterVersionState = 2
	// The cluster version is not available for new clusters; visible for lookups only.
	//
	// New cluster creation with this version is rejected. If the version was the default, `is_default`
	// is auto-cleared. The obsolescence_timestamp is set automatically on transition to this state.
	ClusterVersionState_CLUSTER_VERSION_STATE_OBSOLETE ClusterVersionState = 3
)

// Enum value maps for ClusterVersionState.
var (
	ClusterVersionState_name = map[int32]string{
		0: "CLUSTER_VERSION_STATE_UNSPECIFIED",
		1: "CLUSTER_VERSION_STATE_ACTIVE",
		2: "CLUSTER_VERSION_STATE_DEPRECATED",
		3: "CLUSTER_VERSION_STATE_OBSOLETE",
	}
	ClusterVersionState_value = map[string]int32{
		"CLUSTER_VERSION_STATE_UNSPECIFIED": 0,
		"CLUSTER_VERSION_STATE_ACTIVE":      1,
		"CLUSTER_VERSION_STATE_DEPRECATED":  2,
		"CLUSTER_VERSION_STATE_OBSOLETE":    3,
	}
)

func (x ClusterVersionState) Enum() *ClusterVersionState {
	p := new(ClusterVersionState)
	*p = x
	return p
}

func (x ClusterVersionState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClusterVersionState) Descriptor() protoreflect.EnumDescriptor {
	return file_osac_private_v1_cluster_version_type_proto_enumTypes[0].Descriptor()
}

func (ClusterVersionState) Type() protoreflect.EnumType {
	return &file_osac_private_v1_cluster_version_type_proto_enumTypes[0]
}

func (x ClusterVersionState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Contains deprecation details for a cluster version.
//
// The timestamps are managed by the server during lifecycle state transitions. The deprecation_timestamp is set when
// the version transitions to DEPRECATED, and the obsolescence_timestamp is set when it transitions to OBSOLETE.
// Timestamps are retained as historical record when the version returns to ACTIVE.
type ClusterVersionDeprecation struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// When deprecation was announced. Auto-set on transition to DEPRECATED.
	DeprecationTimestamp *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=deprecation_timestamp,json=deprecationTimestamp,proto3" json:"deprecation_timestamp,omitempty"`
	// When the cluster version becomes or became obsolete. Auto-set on transition to OBSOLETE.
	ObsolescenceTimestamp *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=obsolescence_timestamp,json=obsolescenceTimestamp,proto3" json:"obsolescence_timestamp,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ClusterVersionDeprecation) Reset() {
	*x = ClusterVersionDeprecation{}
	mi := &file_osac_private_v1_cluster_version_type_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterVersionDeprecation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterVersionDeprecation) ProtoMessage() {}

func (x *ClusterVersionDeprecation) ProtoReflect() protoreflect.Message {
	mi := &file_osac_private_v1_cluster_version_type_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ClusterVersionDeprecation) GetDeprecationTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.DeprecationTimestamp
	}
	return nil
}

func (x *ClusterVersionDeprecation) GetObsolescenceTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.ObsolescenceTimestamp
	}
	return nil
}

func (x *ClusterVersionDeprecation) SetDeprecationTimestamp(v *timestamppb.Timestamp) {
	x.DeprecationTimestamp = v
}

func (x *ClusterVersionDeprecation) SetObsolescenceTimestamp(v *timestamppb.Timestamp) {
	x.ObsolescenceTimestamp = v
}

func (x *ClusterVersionDeprecation) HasDeprecationTimestamp() bool {
	if x == nil {
		return false
	}
	return x.DeprecationTimestamp != nil
}

func (x *ClusterVersionDeprecation) HasObsolescenceTimestamp() bool {
	if x == nil {
		return false
	}
	return x.ObsolescenceTimestamp != nil
}

func (x *ClusterVersionDeprecation) ClearDeprecationTimestamp() {
	x.DeprecationTimestamp = nil
}

func (x *ClusterVersionDeprecation) ClearObsolescenceTimestamp() {
	x.ObsolescenceTimestamp = nil
}

type ClusterVersionDeprecation_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// When deprecation was announced. Auto-set on transition to DEPRECATED.
	DeprecationTimestamp *timestamppb.Timestamp
	// When the cluster version becomes or became obsolete. Auto-set on transition to OBSOLETE.
	ObsolescenceTimestamp *timestamppb.Timestamp
}

func (b0 ClusterVersionDeprecation_builder) Build() *ClusterVersionDeprecation {
	m0 := &ClusterVersionDeprecation{}
	b, x := &b0, m0
	_, _ = b, x
	x.DeprecationTimestamp = b.DeprecationTimestamp
	x.ObsolescenceTimestamp = b.ObsolescenceTimestamp
	return m0
}

// Constrains which cluster versions are valid upgrade targets from a given version.
//
// Three-way semantics apply:
// - Message absent: no path constraint is enforced (the target must still be enabled and not obsolete).
// - Message present with empty version_names: no valid targets exist and version change is rejected.
// - Message present with version_names: only the listed versions are accepted as upgrade targets.
type ClusterVersionAllowedUpgrades struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// ClusterVersion names (metadata.name). Must reference existing, non-deleted ClusterVersions. When a target
	// version is deleted, it is automatically removed from all lists.
	VersionNames  []string `protobuf:"bytes,1,rep,name=version_names,json=versionNames,proto3" json:"version_names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterVersionAllowedUpgrades) Reset() {
	*x = ClusterVersionAllowedUpgrades{}
	mi := &file_osac_private_v1_cluster_version_type_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterVersionAllowedUpgrades) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterVersionAllowedUpgrades) ProtoMessage() {}

func (x *ClusterVersionAllowedUpgrades) ProtoReflect() protoreflect.Message {
	mi := &file_osac_private_v1_cluster_version_type_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ClusterVersionAllowedUpgrades) GetVersionNames() []string {
	if x != nil {
		return x.VersionNames
	}
	return nil
}

func (x *ClusterVersionAllowedUpgrades) SetVersionNames(v []string) {
	x.VersionNames = v
}

type ClusterVersionAllowedUpgrades_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// ClusterVersion names (metadata.name). Must reference existing, non-deleted ClusterVersions. When a target
	// version is deleted, it is automatically removed from all lists.
	VersionNames []string
}

func (b0 ClusterVersionAllowedUpgrades_builder) Build() *ClusterVersionAllowedUpgrades {
	m0 := &ClusterVersionAllowedUpgrades{}
	b, x := &b0, m0
	_, _ = b, x
	x.VersionNames = b.VersionNames
	return m0
}

// Contains the details about the cluster version that are available only for the system.
//
// Cluster versions are admin-managed catalog entries that define which OpenShift versions are available. Users
// select a cluster version by name when creating clusters, either directly via Cluster `spec.version_name` or
// through a ClusterTemplate `spec_defaults.version_name`. Cloud Provider Admins control the version catalog
// through lifecycle-managed cluster versions.
//
// If `metadata.name` is omitted on creation, it is auto-generated from `spec.version` by lowercasing and
// replacing non-alphanumeric characters with dashes (e.g., "4.17.0" becomes "4-17-0").
//
// Lifecycle follows: ACTIVE -> DEPRECATED -> OBSOLETE. All transitions between states are allowed.
// Deletion is rejected if the version is referenced by active clusters, templates, or catalog items.
//
// The `spec` contains the desired configuration, and may be modified by the admin. The `status` contains the
// current state of the cluster version, is provided by the system and can't be modified by the user.
type ClusterVersion struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Unique identifier of the cluster version.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Metadata of the cluster version, including name, labels, tenant, and timestamps.
	Metadata *Metadata `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// Desired configuration of the cluster version (admin-modifiable).
	Spec *ClusterVersionSpec `protobuf:"bytes,3,opt,name=spec,proto3" json:"spec,omitempty"`
	// Current state of the cluster version (system-provided, read-only).
	Status        *ClusterVersionStatus `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterVersion) Reset() {
	*x = ClusterVersion{}
	mi := &file_osac_private_v1_cluster_version_type_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterVersion) ProtoMessage() {}

func (x *ClusterVersion) ProtoReflect() protoreflect.Message {
	mi := &file_osac_private_v1_cluster_version_type_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ClusterVersion) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ClusterVersion) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ClusterVersion) GetSpec() *ClusterVersionSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *ClusterVersion) GetStatus() *ClusterVersionStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *ClusterVersion) SetId(v string) {
	x.Id = v
}

func (x *ClusterVersion) SetMetadata(v *Metadata) {
	x.Metadata = v
}

func (x *ClusterVersion) SetSpec(v *ClusterVersionSpec) {
	x.Spec = v
}

func (x *ClusterVersion) SetStatus(v *ClusterVersionStatus) {
	x.Status = v
}

func (x *ClusterVersion) HasMetadata() bool {
	if x == nil {
		return false
	}
	return x.Metadata != nil
}

func (x *ClusterVersion) HasSpec() bool {
	if x == nil {
		return false
	}
	return x.Spec != nil
}

func (x *ClusterVersion) HasStatus() bool {
	if x == nil {
		return false
	}
	return x.Status != nil
}

func (x *ClusterVersion) ClearMetadata() {
	x.Metadata = nil
}

func (x *ClusterVersion) ClearSpec() {
	x.Spec = nil
}

func (x *ClusterVersion) ClearStatus() {
	x.Status = nil
}

type ClusterVersion_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Unique identifier of the cluster version.
	Id string
	// Metadata of the cluster version, including name, labels, tenant, and timestamps.
	Metadata *Metadata
	// Desired configuration of the cluster version (admin-modifiable).
	Spec *ClusterVersionSpec
	// Current state of the cluster version (system-provided, read-only).
	Status *ClusterVersionStatus
}

func (b0 ClusterVersion_builder) Build() *ClusterVersion {
	m0 := &ClusterVersion{}
	b, x := &b0, m0
	_, _ = b, x
	x.Id = b.Id
	x.Metadata = b.Metadata
	x.Spec = b.Spec
	x.Status = b.Status
	return m0
}

// Defines the desired configuration for a ClusterVersion.
//
// The spec contains admin-specified parameters that define the version catalog entry. The `image` and `version`
// fields are immutable after creation. The `enabled`, `is_default`, `state`, `deprecation`, and `allowed_upgrades`
// fields may be updated to manage the version lifecycle.
type ClusterVersionSpec struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// OCI release image pullspec for this version. Required on creation, immutable afterwards.
	//
	// The cluster controller resolves this image when building the ClusterOrder for provisioning.
	//
	// Example: "quay.io/openshift-release-dev/ocp-release:4.17.0-multi"
	Image string `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	// Controls whether new clusters may select this version. Defaults to true on creation.
	//
	// Setting to false prevents new cluster creation with this version. If the version was the default,
	// `is_default` is auto-cleared.
	Enabled *bool `protobuf:"varint,2,opt,name=enabled,proto3,oneof" json:"enabled,omitempty"`
	// At most one active ClusterVersion may be the default. Setting this to true on one version clears it on
	// the previous default atomically. Auto-cleared when the version becomes OBSOLETE or disabled.
	//
	// When creating a cluster, the version is resolved with the following precedence:
	// explicit `spec.version_name` > template `spec_defaults.version_name` > system default (`is_default=true`).
	IsDefault *bool `protobuf:"varint,3,opt,name=is_default,json=isDefault,proto3,oneof" json:"is_default,omitempty"`
	// Current lifecycle state of the cluster version. Defaults to ACTIVE on creation if unspecified.
	State ClusterVersionState `protobuf:"varint,4,opt,name=state,proto3,enum=osac.private.v1.ClusterVersionState" json:"state,omitempty"`
	// Deprecation details. Only meaningful when state is DEPRECATED or OBSOLETE.
	Deprecation *ClusterVersionDeprecation `protobuf:"bytes,5,opt,name=deprecation,proto3" json:"deprecation,omitempty"`
	// Stable semver identifier for this version. Required on creation, immutable afterwards.
	//
	// Must be a valid SemVer 2.0.0 string, max 256 characters. Must be unique among active (non-deleted)
	// ClusterVersions.
	//
	// Example: "4.17.0", "4.17.0-rc.1"
	Version string `protobuf:"bytes,6,opt,name=version,proto3" json:"version,omitempty"`
	// Constrains which versions are valid upgrade targets from this version.
	//
	// When absent, any enabled non-obsolete version is a valid target. When present with an empty list,
	// version changes are blocked. When present with entries, only the listed versions are accepted.
	AllowedUpgrades *ClusterVersionAllowedUpgrades `protobuf:"bytes,7,opt,name=allowed_upgrades,json=allowedUpgrades,proto3" json:"allowed_upgrades,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ClusterVersionSpec) Reset() {
	*x = ClusterVersionSpec{}
	mi := &file_osac_private_v1_cluster_version_type_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterVersionSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterVersionSpec) ProtoMessage() {}

func (x *ClusterVersionSpec) ProtoReflect() protoreflect.Message {
	mi := &file_osac_private_v1_cluster_version_type_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ClusterVersionSpec) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *ClusterVersionSpec) GetEnabled() bool {
	if x != nil && x.Enabled != nil {
		return *x.Enabled
	}
	return false
}

func (x *ClusterVersionSpec) GetIsDefault() bool {
	if x != nil && x.IsDefault != nil {
		return *x.IsDefault
	}
	return false
}

func (x *ClusterVersionSpec) GetState() ClusterVersionState {
	if x != nil {
		return x.State
	}
	return ClusterVersionState_CLUSTER_VERSION_STATE_UNSPECIFIED
}

func (x *ClusterVersionSpec) GetDeprecation() *ClusterVersionDeprecation {
	if x != nil {
		return x.Deprecation
	}
	return nil
}

func (x *ClusterVersionSpec) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ClusterVersionSpec) GetAllowedUpgrades() *ClusterVersionAllowedUpgrades {
	if x != nil {
		return x.AllowedUpgrades
	}
	return nil
}

func (x *ClusterVersionSpec) SetImage(v string) {
	x.Image = v
}

func (x *ClusterVersionSpec) SetEnabled(v bool) {
	x.Enabled = &v
}

func (x *ClusterVersionSpec) SetIsDefault(v bool) {
	x.IsDefault = &v
}

func (x *ClusterVersionSpec) SetState(v ClusterVersionState) {
	x.State = v
}

func (x *ClusterVersionSpec) SetDeprecation(v *ClusterVersionDeprecation) {
	x.Deprecation = v
}

func (x *ClusterVersionSpec) SetVersion(v string) {
	x.Version = v
}

func (x *ClusterVersionSpec) SetAllowedUpgrades(v *ClusterVersionAllowedUpgrades) {
	x.AllowedUpgrades = v
}

func (x *ClusterVersionSpec) HasEnabled() bool {
	if x == nil {
		return false
	}
	return x.Enabled != nil
}

func (x *ClusterVersionSpec) HasIsDefault() bool {
	if x == nil {
		return false
	}
	return x.IsDefault != nil
}

func (x *ClusterVersionSpec) HasDeprecation() bool {
	if x == nil {
		return false
	}
	return x.Deprecation != nil
}

func (x *ClusterVersionSpec) HasAllowedUpgrades() bool {
	if x == nil {
		return false
	}
	return x.AllowedUpgrades != nil
}

func (x *ClusterVersionSpec) ClearEnabled() {
	x.Enabled = nil
}

func (x *ClusterVersionSpec) ClearIsDefault() {
	x.IsDefault = nil
}

func (x *ClusterVersionSpec) ClearDeprecation() {
	x.Deprecation = nil
}

func (x *ClusterVersionSpec) ClearAllowedUpgrades() {
	x.AllowedUpgrades = nil
}

type ClusterVersionSpec_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// OCI release image pullspec for this version. Required on creation, immutable afterwards.
	//
	// The cluster controller resolves this image when building the ClusterOrder for provisioning.
	//
	// Example: "quay.io/openshift-release-dev/ocp-release:4.17.0-multi"
	Image string
	// Controls whether new clusters may select this version. Defaults to true on creation.
	//
	// Setting to false prevents new cluster creation with this version. If the version was the default,
	// `is_default` is auto-cleared.
	Enabled *bool
	// At most one active ClusterVersion may be the default. Setting this to true on one version clears it on
	// the previous default atomically. Auto-cleared when the version becomes OBSOLETE or disabled.
	//
	// When creating a cluster, the version is resolved with the following precedence:
	// explicit `spec.version_name` > template `spec_defaults.version_name` > system default (`is_default=true`).
	IsDefault *bool
	// Current lifecycle state of the cluster version. Defaults to ACTIVE on creation if unspecified.
	State ClusterVersionState
	// Deprecation details. Only meaningful when state is DEPRECATED or OBSOLETE.
	Deprecation *ClusterVersionDeprecation
	// Stable semver identifier for this version. Required on creation, immutable afterwards.
	//
	// Must be a valid SemVer 2.0.0 string, max 256 characters. Must be unique among active (non-deleted)
	// ClusterVersions.
	//
	// Example: "4.17.0", "4.17.0-rc.1"
	Version string
	// Constrains which versions are valid upgrade targets from this version.
	//
	// When absent, any enabled non-obsolete version is a valid target. When present with an empty list,
	// version changes are blocked. When present with entries, only the listed versions are accepted.
	AllowedUpgrades *ClusterVersionAllowedUpgrades
}

func (b0 ClusterVersionSpec_builder) Build() *ClusterVersionSpec {
	m0 := &ClusterVersionSpec{}
	b, x := &b0, m0
	_, _ = b, x
	x.Image = b.Image
	x.Enabled = b.Enabled
	x.IsDefault = b.IsDefault
	x.State = b.State
	x.Deprecation = b.Deprecation
	x.Version = b.Version
	x.AllowedUpgrades = b.AllowedUpgrades
	return m0
}

// Contains the system-provided status of a ClusterVersion.
//
// Currently empty. Reserved for future use.
type ClusterVersionStatus struct {
	state         protoimpl.MessageState `protogen:"hybrid.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterVersionStatus) Reset() {
	*x = ClusterVersionStatus{}
	mi := &file_osac_private_v1_cluster_version_type_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterVersionStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterVersionStatus) ProtoMessage() {}

func (x *ClusterVersionStatus) ProtoReflect() protoreflect.Message {
	mi := &file_osac_private_v1_cluster_version_type_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type ClusterVersionStatus_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 ClusterVersionStatus_builder) Build() *ClusterVersionStatus {
	m0 := &ClusterVersionStatus{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

var File_osac_private_v1_cluster_version_type_proto protoreflect.FileDescriptor

var file_osac_private_v1_cluster_version_type_proto_rawDesc = string([]byte{
	0x0a, 0x2a, 0x6f, 0x73, 0x61, 0x63, 0x2f, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2f, 0x76,
	0x31, 0x2f, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x6f, 0x73,
	0x61, 0x63, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x1a, 0x1f, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x5f,
	0x62, 0x65, 0x68, 0x61, 0x76, 0x69, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x23, 0x6f, 0x73, 0x61, 0x63, 0x2f, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x31,
	0x2f, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0xc9, 0x01, 0x0a, 0x19, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72,
	0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x44, 0x65, 0x70, 0x72, 0x65, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x54, 0x0a, 0x15, 0x64, 0x65, 0x70, 0x72, 0x65, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x42, 0x03, 0xe0,
	0x41, 0x03, 0x52, 0x14, 0x64, 0x65, 0x70, 0x72, 0x65, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x56, 0x0a, 0x16, 0x6f, 0x62, 0x73, 0x6f,
	0x6c, 0x65, 0x73, 0x63, 0x65, 0x6e, 0x63, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x42, 0x03, 0xe0, 0x41, 0x03, 0x52, 0x15, 0x6f, 0x62, 0x73, 0x6f, 0x6c,
	0x65, 0x73, 0x63, 0x65, 0x6e, 0x63, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x22, 0x44, 0x0a, 0x1d, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x56, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x41, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64, 0x55, 0x70, 0x67, 0x72, 0x61, 0x64, 0x65,
	0x73, 0x12, 0x23, 0x0a, 0x0d, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0c, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x22, 0xcf, 0x01, 0x0a, 0x0e, 0x43, 0x6c, 0x75, 0x73, 0x74,
	0x65, 0x72, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x35, 0x0a, 0x08, 0x6d, 0x65, 0x74,
	0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6f, 0x73,
	0x61, 0x63, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x65,
	0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61,
	0x12, 0x37, 0x0a, 0x04, 0x73, 0x70, 0x65, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23,
	0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31,
	0x2e, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x53,
	0x70, 0x65, 0x63, 0x52, 0x04, 0x73, 0x70, 0x65, 0x63, 0x12, 0x3d, 0x0a, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x6f, 0x73, 0x61, 0x63,
	0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6c, 0x75, 0x73,
	0x74, 0x65, 0x72, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0xb0, 0x03, 0x0a, 0x12, 0x43, 0x6c, 0x75,
	0x73, 0x74, 0x65, 0x72, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x53, 0x70, 0x65, 0x63, 0x12,
	0x1c, 0x0a, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x06,
	0xe0, 0x41, 0x02, 0xe0, 0x41, 0x05, 0x52, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x22, 0x0a,
	0x07, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x42, 0x03,
	0xe0, 0x41, 0x01, 0x48, 0x00, 0x52, 0x07, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x88, 0x01,
	0x01, 0x12, 0x27, 0x0a, 0x0a, 0x69, 0x73, 0x5f, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x08, 0x42, 0x03, 0xe0, 0x41, 0x01, 0x48, 0x01, 0x52, 0x09, 0x69, 0x73,
	0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x88, 0x01, 0x01, 0x12, 0x3f, 0x0a, 0x05, 0x73, 0x74,
	0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x24, 0x2e, 0x6f, 0x73, 0x61, 0x63,
	0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6c, 0x75, 0x73,
	0x74, 0x65, 0x72, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x42,
	0x03, 0xe0, 0x41, 0x01, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x51, 0x0a, 0x0b, 0x64,
	0x65, 0x70, 0x72, 0x65, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x2a, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e,
	0x76, 0x31, 0x2e, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x44, 0x65, 0x70, 0x72, 0x65, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x03, 0xe0, 0x41,
	0x01, 0x52, 0x0b, 0x64, 0x65, 0x70, 0x72, 0x65, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x20,
	0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x42,
	0x06, 0xe0, 0x41, 0x02, 0xe0, 0x41, 0x05, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x12, 0x5e, 0x0a, 0x10, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64, 0x5f, 0x75, 0x70, 0x67, 0x72,
	0x61, 0x64, 0x65, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2e, 0x2e, 0x6f, 0x73, 0x61,
	0x63, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6c, 0x75,
	0x73, 0x74, 0x65, 0x72, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x41, 0x6c, 0x6c, 0x6f, 0x77,
	0x65, 0x64, 0x55, 0x70, 0x67, 0x72, 0x61, 0x64, 0x65, 0x73, 0x42, 0x03, 0xe0, 0x41, 0x01, 0x52,
	0x0f, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64, 0x55, 0x70, 0x67, 0x72, 0x61, 0x64, 0x65, 0x73,
	0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x42, 0x0d, 0x0a, 0x0b,
	0x5f, 0x69, 0x73, 0x5f, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x22, 0x16, 0x0a, 0x14, 0x43,
	0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x2a, 0xa8, 0x01, 0x0a, 0x13, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x56,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x25, 0x0a, 0x21, 0x43,
	0x4c, 0x55, 0x53, 0x54, 0x45, 0x52, 0x5f, 0x56, 0x45, 0x52, 0x53, 0x49, 0x4f, 0x4e, 0x5f, 0x53,
	0x54, 0x41, 0x54, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44,
	0x10, 0x00, 0x12, 0x20, 0x0a, 0x1c, 0x43, 0x4c, 0x55, 0x53, 0x54, 0x45, 0x52, 0x5f, 0x56, 0x45,
	0x52, 0x53, 0x49, 0x4f, 0x4e, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x41, 0x43, 0x54, 0x49,
	0x56, 0x45, 0x10, 0x01, 0x12, 0x24, 0x0a, 0x20, 0x43, 0x4c, 0x55, 0x53, 0x54, 0x45, 0x52, 0x5f,
	0x56, 0x45, 0x52, 0x53, 0x49, 0x4f, 0x4e, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x44, 0x45,
	0x50, 0x52, 0x45, 0x43, 0x41, 0x54, 0x45, 0x44, 0x10, 0x02, 0x12, 0x22, 0x0a, 0x1e, 0x43, 0x4c,
	0x55, 0x53, 0x54, 0x45, 0x52, 0x5f, 0x56, 0x45, 0x52, 0x53, 0x49, 0x4f, 0x4e, 0x5f, 0x53, 0x54,
	0x41, 0x54, 0x45, 0x5f, 0x4f, 0x42, 0x53, 0x4f, 0x4c, 0x45, 0x54, 0x45, 0x10, 0x03, 0x42, 0xe2,
	0x01, 0x0a, 0x13, 0x63, 0x6f, 0x6d, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x72, 0x69, 0x76,
	0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x42, 0x17, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x56,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50,
	0x01, 0x5a, 0x52, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x73,
	0x61, 0x63, 0x2d, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x2f, 0x66, 0x75, 0x6c, 0x66, 0x69,
	0x6c, 0x6c, 0x6d, 0x65, 0x6e, 0x74, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x69,
	0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6f, 0x73, 0x61, 0x63,
	0x2f, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x31, 0x3b, 0x70, 0x72, 0x69, 0x76,
	0x61, 0x74, 0x65, 0x76, 0x31, 0xa2, 0x02, 0x03, 0x4f, 0x50, 0x58, 0xaa, 0x02, 0x0f, 0x4f, 0x73,
	0x61, 0x63, 0x2e, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x56, 0x31, 0xca, 0x02, 0x10,
	0x4f, 0x73, 0x61, 0x63, 0x5c, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x5f, 0x5c, 0x56, 0x31,
	0xe2, 0x02, 0x1c, 0x4f, 0x73, 0x61, 0x63, 0x5c, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x5f,
	0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea,
	0x02, 0x11, 0x4f, 0x73, 0x61, 0x63, 0x3a, 0x3a, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x3a,
	0x3a, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var file_osac_private_v1_cluster_version_type_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_osac_private_v1_cluster_version_type_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_osac_private_v1_cluster_version_type_proto_goTypes = []any{
	(ClusterVersionState)(0),              // 0: osac.private.v1.ClusterVersionState
	(*ClusterVersionDeprecation)(nil),     // 1: osac.private.v1.ClusterVersionDeprecation
	(*ClusterVersionAllowedUpgrades)(nil), // 2: osac.private.v1.ClusterVersionAllowedUpgrades
	(*ClusterVersion)(nil),                // 3: osac.private.v1.ClusterVersion
	(*ClusterVersionSpec)(nil),            // 4: osac.private.v1.ClusterVersionSpec
	(*ClusterVersionStatus)(nil),          // 5: osac.private.v1.ClusterVersionStatus
	(*timestamppb.Timestamp)(nil),         // 6: google.protobuf.Timestamp
	(*Metadata)(nil),                      // 7: osac.private.v1.Metadata
}
var file_osac_private_v1_cluster_version_type_proto_depIdxs = []int32{
	6, // 0: osac.private.v1.ClusterVersionDeprecation.deprecation_timestamp:type_name -> google.protobuf.Timestamp
	6, // 1: osac.private.v1.ClusterVersionDeprecation.obsolescence_timestamp:type_name -> google.protobuf.Timestamp
	7, // 2: osac.private.v1.ClusterVersion.metadata:type_name -> osac.private.v1.Metadata
	4, // 3: osac.private.v1.ClusterVersion.spec:type_name -> osac.private.v1.ClusterVersionSpec
	5, // 4: osac.private.v1.ClusterVersion.status:type_name -> osac.private.v1.ClusterVersionStatus
	0, // 5: osac.private.v1.ClusterVersionSpec.state:type_name -> osac.private.v1.ClusterVersionState
	1, // 6: osac.private.v1.ClusterVersionSpec.deprecation:type_name -> osac.private.v1.ClusterVersionDeprecation
	2, // 7: osac.private.v1.ClusterVersionSpec.allowed_upgrades:type_name -> osac.private.v1.ClusterVersionAllowedUpgrades
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_osac_private_v1_cluster_version_type_proto_init() }
func file_osac_private_v1_cluster_version_type_proto_init() {
	if File_osac_private_v1_cluster_version_type_proto != nil {
		return
	}
	file_osac_private_v1_metadata_type_proto_init()
	file_osac_private_v1_cluster_version_type_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_osac_private_v1_cluster_version_type_proto_rawDesc), len(file_osac_private_v1_cluster_version_type_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_osac_private_v1_cluster_version_type_proto_goTypes,
		DependencyIndexes: file_osac_private_v1_cluster_version_type_proto_depIdxs,
		EnumInfos:         file_osac_private_v1_cluster_version_type_proto_enumTypes,
		MessageInfos:      file_osac_private_v1_cluster_version_type_proto_msgTypes,
	}.Build()
	File_osac_private_v1_cluster_version_type_proto = out.File
	file_osac_private_v1_cluster_version_type_proto_goTypes = nil
	file_osac_private_v1_cluster_version_type_proto_depIdxs = nil
}
