//
// Copyright (c) 2026 Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        (unknown)
// source: osac/private/v1/project_membership_type.proto

//go:build !protoopaque

package privatev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Describes the role of a member in a project.
type ProjectMembershipRole int32

const (
	// Default value, should not be used.
	ProjectMembershipRole_PROJECT_MEMBERSHIP_ROLE_UNSPECIFIED ProjectMembershipRole = 0
	// The member can view the project and its resources.
	ProjectMembershipRole_PROJECT_MEMBERSHIP_ROLE_VIEWER ProjectMembershipRole = 1
	// The member can manage the project, including adding/removing other members.
	ProjectMembershipRole_PROJECT_MEMBERSHIP_ROLE_MANAGER ProjectMembershipRole = 2
)

// Enum value maps for ProjectMembershipRole.
var (
	ProjectMembershipRole_name = map[int32]string{
		0: "PROJECT_MEMBERSHIP_ROLE_UNSPECIFIED",
		1: "PROJECT_MEMBERSHIP_ROLE_VIEWER",
		2: "PROJECT_MEMBERSHIP_ROLE_MANAGER",
	}
	ProjectMembershipRole_value = map[string]int32{
		"PROJECT_MEMBERSHIP_ROLE_UNSPECIFIED": 0,
		"PROJECT_MEMBERSHIP_ROLE_VIEWER":      1,
		"PROJECT_MEMBERSHIP_ROLE_MANAGER":     2,
	}
)

func (x ProjectMembershipRole) Enum() *ProjectMembershipRole {
	p := new(ProjectMembershipRole)
	*p = x
	return p
}

func (x ProjectMembershipRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProjectMembershipRole) Descriptor() protoreflect.EnumDescriptor {
	return file_osac_private_v1_project_membership_type_proto_enumTypes[0].Descriptor()
}

func (ProjectMembershipRole) Type() protoreflect.EnumType {
	return &file_osac_private_v1_project_membership_type_proto_enumTypes[0]
}

func (x ProjectMembershipRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Describes the state of a project membership.
type ProjectMembershipState int32

const (
	// Default value, should not be used.
	ProjectMembershipState_PROJECT_MEMBERSHIP_STATE_UNSPECIFIED ProjectMembershipState = 0
	// The project membership is pending synchronization with the identity provider.
	ProjectMembershipState_PROJECT_MEMBERSHIP_STATE_PENDING ProjectMembershipState = 1
	// The project membership is ready and the member has the specified permissions.
	ProjectMembershipState_PROJECT_MEMBERSHIP_STATE_READY ProjectMembershipState = 2
	// The project membership failed to synchronize with the identity provider.
	ProjectMembershipState_PROJECT_MEMBERSHIP_STATE_FAILED ProjectMembershipState = 3
)

// Enum value maps for ProjectMembershipState.
var (
	ProjectMembershipState_name = map[int32]string{
		0: "PROJECT_MEMBERSHIP_STATE_UNSPECIFIED",
		1: "PROJECT_MEMBERSHIP_STATE_PENDING",
		2: "PROJECT_MEMBERSHIP_STATE_READY",
		3: "PROJECT_MEMBERSHIP_STATE_FAILED",
	}
	ProjectMembershipState_value = map[string]int32{
		"PROJECT_MEMBERSHIP_STATE_UNSPECIFIED": 0,
		"PROJECT_MEMBERSHIP_STATE_PENDING":     1,
		"PROJECT_MEMBERSHIP_STATE_READY":       2,
		"PROJECT_MEMBERSHIP_STATE_FAILED":      3,
	}
)

func (x ProjectMembershipState) Enum() *ProjectMembershipState {
	p := new(ProjectMembershipState)
	*p = x
	return p
}

func (x ProjectMembershipState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProjectMembershipState) Descriptor() protoreflect.EnumDescriptor {
	return file_osac_private_v1_project_membership_type_proto_enumTypes[1].Descriptor()
}

func (ProjectMembershipState) Type() protoreflect.EnumType {
	return &file_osac_private_v1_project_membership_type_proto_enumTypes[1]
}

func (x ProjectMembershipState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// ProjectMembership represents a member's association with a project and their role within it.
type ProjectMembership struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Unique identifier of the project membership.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Object metadata.
	Metadata *Metadata `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// Desired state of the project membership.
	Spec *ProjectMembershipSpec `protobuf:"bytes,3,opt,name=spec,proto3" json:"spec,omitempty"`
	// Observed state of the project membership.
	Status        *ProjectMembershipStatus `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectMembership) Reset() {
	*x = ProjectMembership{}
	mi := &file_osac_private_v1_project_membership_type_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectMembership) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectMembership) ProtoMessage() {}

func (x *ProjectMembership) ProtoReflect() protoreflect.Message {
	mi := &file_osac_private_v1_project_membership_type_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ProjectMembership) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProjectMembership) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ProjectMembership) GetSpec() *ProjectMembershipSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *ProjectMembership) GetStatus() *ProjectMembershipStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *ProjectMembership) SetId(v string) {
	x.Id = v
}

func (x *ProjectMembership) SetMetadata(v *Metadata) {
	x.Metadata = v
}

func (x *ProjectMembership) SetSpec(v *ProjectMembershipSpec) {
	x.Spec = v
}

func (x *ProjectMembership) SetStatus(v *ProjectMembershipStatus) {
	x.Status = v
}

func (x *ProjectMembership) HasMetadata() bool {
	if x == nil {
		return false
	}
	return x.Metadata != nil
}

func (x *ProjectMembership) HasSpec() bool {
	if x == nil {
		return false
	}
	return x.Spec != nil
}

func (x *ProjectMembership) HasStatus() bool {
	if x == nil {
		return false
	}
	return x.Status != nil
}

func (x *ProjectMembership) ClearMetadata() {
	x.Metadata = nil
}

func (x *ProjectMembership) ClearSpec() {
	x.Spec = nil
}

func (x *ProjectMembership) ClearStatus() {
	x.Status = nil
}

type ProjectMembership_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Unique identifier of the project membership.
	Id string
	// Object metadata.
	Metadata *Metadata
	// Desired state of the project membership.
	Spec *ProjectMembershipSpec
	// Observed state of the project membership.
	Status *ProjectMembershipStatus
}

func (b0 ProjectMembership_builder) Build() *ProjectMembership {
	m0 := &ProjectMembership{}
	b, x := &b0, m0
	_, _ = b, x
	x.Id = b.Id
	x.Metadata = b.Metadata
	x.Spec = b.Spec
	x.Status = b.Status
	return m0
}

// Describes a member of a project.
type ProjectMembershipSpec struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Role of the member in the project. This indicates whether the member is a viewer, manager, etc.
	Role ProjectMembershipRole `protobuf:"varint,2,opt,name=role,proto3,enum=osac.private.v1.ProjectMembershipRole" json:"role,omitempty"`
	// Unique identifier of the member. Currently members are users (referenced by their User object ID), but this leaves
	// room for adding other kinds of members in the future, like groups.
	//
	// Types that are valid to be assigned to Member:
	//
	//	*ProjectMembershipSpec_User
	Member        isProjectMembershipSpec_Member `protobuf_oneof:"member"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectMembershipSpec) Reset() {
	*x = ProjectMembershipSpec{}
	mi := &file_osac_private_v1_project_membership_type_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectMembershipSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectMembershipSpec) ProtoMessage() {}

func (x *ProjectMembershipSpec) ProtoReflect() protoreflect.Message {
	mi := &file_osac_private_v1_project_membership_type_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ProjectMembershipSpec) GetRole() ProjectMembershipRole {
	if x != nil {
		return x.Role
	}
	return ProjectMembershipRole_PROJECT_MEMBERSHIP_ROLE_UNSPECIFIED
}

func (x *ProjectMembershipSpec) GetMember() isProjectMembershipSpec_Member {
	if x != nil {
		return x.Member
	}
	return nil
}

func (x *ProjectMembershipSpec) GetUser() string {
	if x != nil {
		if x, ok := x.Member.(*ProjectMembershipSpec_User); ok {
			return x.User
		}
	}
	return ""
}

func (x *ProjectMembershipSpec) SetRole(v ProjectMembershipRole) {
	x.Role = v
}

func (x *ProjectMembershipSpec) SetUser(v string) {
	x.Member = &ProjectMembershipSpec_User{v}
}

func (x *ProjectMembershipSpec) HasMember() bool {
	if x == nil {
		return false
	}
	return x.Member != nil
}

func (x *ProjectMembershipSpec) HasUser() bool {
	if x == nil {
		return false
	}
	_, ok := x.Member.(*ProjectMembershipSpec_User)
	return ok
}

func (x *ProjectMembershipSpec) ClearMember() {
	x.Member = nil
}

func (x *ProjectMembershipSpec) ClearUser() {
	if _, ok := x.Member.(*ProjectMembershipSpec_User); ok {
		x.Member = nil
	}
}

const ProjectMembershipSpec_Member_not_set_case case_ProjectMembershipSpec_Member = 0
const ProjectMembershipSpec_User_case case_ProjectMembershipSpec_Member = 3

func (x *ProjectMembershipSpec) WhichMember() case_ProjectMembershipSpec_Member {
	if x == nil {
		return ProjectMembershipSpec_Member_not_set_case
	}
	switch x.Member.(type) {
	case *ProjectMembershipSpec_User:
		return ProjectMembershipSpec_User_case
	default:
		return ProjectMembershipSpec_Member_not_set_case
	}
}

type ProjectMembershipSpec_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Role of the member in the project. This indicates whether the member is a viewer, manager, etc.
	Role ProjectMembershipRole
	// Unique identifier of the member. Currently members are users (referenced by their User object ID), but this leaves
	// room for adding other kinds of members in the future, like groups.

	// Fields of oneof Member:
	User *string
	// -- end of Member
}

func (b0 ProjectMembershipSpec_builder) Build() *ProjectMembershipSpec {
	m0 := &ProjectMembershipSpec{}
	b, x := &b0, m0
	_, _ = b, x
	x.Role = b.Role
	if b.User != nil {
		x.Member = &ProjectMembershipSpec_User{*b.User}
	}
	return m0
}

type case_ProjectMembershipSpec_Member protoreflect.FieldNumber

func (x case_ProjectMembershipSpec_Member) String() string {
	md := file_osac_private_v1_project_membership_type_proto_msgTypes[1].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isProjectMembershipSpec_Member interface {
	isProjectMembershipSpec_Member()
}

type ProjectMembershipSpec_User struct {
	User string `protobuf:"bytes,3,opt,name=user,proto3,oneof"`
}

func (*ProjectMembershipSpec_User) isProjectMembershipSpec_Member() {}

// Describes the observed state of a project membership.
type ProjectMembershipStatus struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Current state of the project membership.
	State ProjectMembershipState `protobuf:"varint,1,opt,name=state,proto3,enum=osac.private.v1.ProjectMembershipState" json:"state,omitempty"`
	// Human-readable message providing additional details about the current state. For example, if the state is
	// FAILED, this field may explain why the synchronization with the identity provider failed.
	Message       *string `protobuf:"bytes,2,opt,name=message,proto3,oneof" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectMembershipStatus) Reset() {
	*x = ProjectMembershipStatus{}
	mi := &file_osac_private_v1_project_membership_type_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectMembershipStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectMembershipStatus) ProtoMessage() {}

func (x *ProjectMembershipStatus) ProtoReflect() protoreflect.Message {
	mi := &file_osac_private_v1_project_membership_type_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ProjectMembershipStatus) GetState() ProjectMembershipState {
	if x != nil {
		return x.State
	}
	return ProjectMembershipState_PROJECT_MEMBERSHIP_STATE_UNSPECIFIED
}

func (x *ProjectMembershipStatus) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

func (x *ProjectMembershipStatus) SetState(v ProjectMembershipState) {
	x.State = v
}

func (x *ProjectMembershipStatus) SetMessage(v string) {
	x.Message = &v
}

func (x *ProjectMembershipStatus) HasMessage() bool {
	if x == nil {
		return false
	}
	return x.Message != nil
}

func (x *ProjectMembershipStatus) ClearMessage() {
	x.Message = nil
}

type ProjectMembershipStatus_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Current state of the project membership.
	State ProjectMembershipState
	// Human-readable message providing additional details about the current state. For example, if the state is
	// FAILED, this field may explain why the synchronization with the identity provider failed.
	Message *string
}

func (b0 ProjectMembershipStatus_builder) Build() *ProjectMembershipStatus {
	m0 := &ProjectMembershipStatus{}
	b, x := &b0, m0
	_, _ = b, x
	x.State = b.State
	x.Message = b.Message
	return m0
}

var File_osac_private_v1_project_membership_type_proto protoreflect.FileDescriptor

var file_osac_private_v1_project_membership_type_proto_rawDesc = string([]byte{
	0x0a, 0x2d, 0x6f, 0x73, 0x61, 0x63, 0x2f, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2f, 0x76,
	0x31, 0x2f, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72,
	0x73, 0x68, 0x69, 0x70, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0f, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31,
	0x1a, 0x23, 0x6f, 0x73, 0x61, 0x63, 0x2f, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2f, 0x76,
	0x31, 0x2f, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xd8, 0x01, 0x0a, 0x11, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63,
	0x74, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x35, 0x0a, 0x08, 0x6d,
	0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e,
	0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e,
	0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0x12, 0x3a, 0x0a, 0x04, 0x73, 0x70, 0x65, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x26, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e,
	0x76, 0x31, 0x2e, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72,
	0x73, 0x68, 0x69, 0x70, 0x53, 0x70, 0x65, 0x63, 0x52, 0x04, 0x73, 0x70, 0x65, 0x63, 0x12, 0x40,
	0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x28,
	0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31,
	0x2e, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x68,
	0x69, 0x70, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x22, 0x73, 0x0a, 0x15, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x4d, 0x65, 0x6d, 0x62, 0x65,
	0x72, 0x73, 0x68, 0x69, 0x70, 0x53, 0x70, 0x65, 0x63, 0x12, 0x3a, 0x0a, 0x04, 0x72, 0x6f, 0x6c,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x26, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70,
	0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63,
	0x74, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x52, 0x6f, 0x6c, 0x65, 0x52,
	0x04, 0x72, 0x6f, 0x6c, 0x65, 0x12, 0x14, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x42, 0x08, 0x0a, 0x06, 0x6d,
	0x65, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x83, 0x01, 0x0a, 0x17, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63,
	0x74, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x3d, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x27, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e,
	0x76, 0x31, 0x2e, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72,
	0x73, 0x68, 0x69, 0x70, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65,
	0x12, 0x1d, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x48, 0x00, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x88, 0x01, 0x01, 0x42,
	0x0a, 0x0a, 0x08, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2a, 0x89, 0x01, 0x0a, 0x15,
	0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x68, 0x69,
	0x70, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x27, 0x0a, 0x23, 0x50, 0x52, 0x4f, 0x4a, 0x45, 0x43, 0x54,
	0x5f, 0x4d, 0x45, 0x4d, 0x42, 0x45, 0x52, 0x53, 0x48, 0x49, 0x50, 0x5f, 0x52, 0x4f, 0x4c, 0x45,
	0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x22,
	0x0a, 0x1e, 0x50, 0x52, 0x4f, 0x4a, 0x45, 0x43, 0x54, 0x5f, 0x4d, 0x45, 0x4d, 0x42, 0x45, 0x52,
	0x53, 0x48, 0x49, 0x50, 0x5f, 0x52, 0x4f, 0x4c, 0x45, 0x5f, 0x56, 0x49, 0x45, 0x57, 0x45, 0x52,
	0x10, 0x01, 0x12, 0x23, 0x0a, 0x1f, 0x50, 0x52, 0x4f, 0x4a, 0x45, 0x43, 0x54, 0x5f, 0x4d, 0x45,
	0x4d, 0x42, 0x45, 0x52, 0x53, 0x48, 0x49, 0x50, 0x5f, 0x52, 0x4f, 0x4c, 0x45, 0x5f, 0x4d, 0x41,
	0x4e, 0x41, 0x47, 0x45, 0x52, 0x10, 0x02, 0x2a, 0xb1, 0x01, 0x0a, 0x16, 0x50, 0x72, 0x6f, 0x6a,
	0x65, 0x63, 0x74, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x12, 0x28, 0x0a, 0x24, 0x50, 0x52, 0x4f, 0x4a, 0x45, 0x43, 0x54, 0x5f, 0x4d, 0x45,
	0x4d, 0x42, 0x45, 0x52, 0x53, 0x48, 0x49, 0x50, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x55,
	0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x24, 0x0a, 0x20,
	0x50, 0x52, 0x4f, 0x4a, 0x45, 0x43, 0x54, 0x5f, 0x4d, 0x45, 0x4d, 0x42, 0x45, 0x52, 0x53, 0x48,
	0x49, 0x50, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x50, 0x45, 0x4e, 0x44, 0x49, 0x4e, 0x47,
	0x10, 0x01, 0x12, 0x22, 0x0a, 0x1e, 0x50, 0x52, 0x4f, 0x4a, 0x45, 0x43, 0x54, 0x5f, 0x4d, 0x45,
	0x4d, 0x42, 0x45, 0x52, 0x53, 0x48, 0x49, 0x50, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x52,
	0x45, 0x41, 0x44, 0x59, 0x10, 0x02, 0x12, 0x23, 0x0a, 0x1f, 0x50, 0x52, 0x4f, 0x4a, 0x45, 0x43,
	0x54, 0x5f, 0x4d, 0x45, 0x4d, 0x42, 0x45, 0x52, 0x53, 0x48, 0x49, 0x50, 0x5f, 0x53, 0x54, 0x41,
	0x54, 0x45, 0x5f, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10, 0x03, 0x42, 0xe5, 0x01, 0x0a, 0x13,
	0x63, 0x6f, 0x6d, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65,
	0x2e, 0x76, 0x31, 0x42, 0x1a, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x4d, 0x65, 0x6d, 0x62,
	0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x54, 0x79, 0x70, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50,
	0x01, 0x5a, 0x52, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x73,
	0x61, 0x63, 0x2d, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x2f, 0x66, 0x75, 0x6c, 0x66, 0x69,
	0x6c, 0x6c, 0x6d, 0x65, 0x6e, 0x74, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x69,
	0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6f, 0x73, 0x61, 0x63,
	0x2f, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x31, 0x3b, 0x70, 0x72, 0x69, 0x76,
	0x61, 0x74, 0x65, 0x76, 0x31, 0xa2, 0x02, 0x03, 0x4f, 0x50, 0x58, 0xaa, 0x02, 0x0f, 0x4f, 0x73,
	0x61, 0x63, 0x2e, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x56, 0x31, 0xca, 0x02, 0x10,
	0x4f, 0x73, 0x61, 0x63, 0x5c, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x5f, 0x5c, 0x56, 0x31,
	0xe2, 0x02, 0x1c, 0x4f, 0x73, 0x61, 0x63, 0x5c, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x5f,
	0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea,
	0x02, 0x11, 0x4f, 0x73, 0x61, 0x63, 0x3a, 0x3a, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x3a,
	0x3a, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var file_osac_private_v1_project_membership_type_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_osac_private_v1_project_membership_type_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_osac_private_v1_project_membership_type_proto_goTypes = []any{
	(ProjectMembershipRole)(0),      // 0: osac.private.v1.ProjectMembershipRole
	(ProjectMembershipState)(0),     // 1: osac.private.v1.ProjectMembershipState
	(*ProjectMembership)(nil),       // 2: osac.private.v1.ProjectMembership
	(*ProjectMembershipSpec)(nil),   // 3: osac.private.v1.ProjectMembershipSpec
	(*ProjectMembershipStatus)(nil), // 4: osac.private.v1.ProjectMembershipStatus
	(*Metadata)(nil),                // 5: osac.private.v1.Metadata
}
var file_osac_private_v1_project_membership_type_proto_depIdxs = []int32{
	5, // 0: osac.private.v1.ProjectMembership.metadata:type_name -> osac.private.v1.Metadata
	3, // 1: osac.private.v1.ProjectMembership.spec:type_name -> osac.private.v1.ProjectMembershipSpec
	4, // 2: osac.private.v1.ProjectMembership.status:type_name -> osac.private.v1.ProjectMembershipStatus
	0, // 3: osac.private.v1.ProjectMembershipSpec.role:type_name -> osac.private.v1.ProjectMembershipRole
	1, // 4: osac.private.v1.ProjectMembershipStatus.state:type_name -> osac.private.v1.ProjectMembershipState
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_osac_private_v1_project_membership_type_proto_init() }
func file_osac_private_v1_project_membership_type_proto_init() {
	if File_osac_private_v1_project_membership_type_proto != nil {
		return
	}
	file_osac_private_v1_metadata_type_proto_init()
	file_osac_private_v1_project_membership_type_proto_msgTypes[1].OneofWrappers = []any{
		(*ProjectMembershipSpec_User)(nil),
	}
	file_osac_private_v1_project_membership_type_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_osac_private_v1_project_membership_type_proto_rawDesc), len(file_osac_private_v1_project_membership_type_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_osac_private_v1_project_membership_type_proto_goTypes,
		DependencyIndexes: file_osac_private_v1_project_membership_type_proto_depIdxs,
		EnumInfos:         file_osac_private_v1_project_membership_type_proto_enumTypes,
		MessageInfos:      file_osac_private_v1_project_membership_type_proto_msgTypes,
	}.Build()
	File_osac_private_v1_project_membership_type_proto = out.File
	file_osac_private_v1_project_membership_type_proto_goTypes = nil
	file_osac_private_v1_project_membership_type_proto_depIdxs = nil
}
