// Code generated by MockGen. DO NOT EDIT.
// Source: ../../api/osac/private/v1/external_ips_service_grpc.pb.go
//
// Generated by this command:
//
//	mockgen -source=../../api/osac/private/v1/external_ips_service_grpc.pb.go -destination=external_ips_client_mock.go -package=externalip ExternalIPsClient
//

// Package externalip is a generated GoMock package.
package externalip

import (
	context "context"
	reflect "reflect"

	privatev1 "github.com/osac-project/fulfillment-service/internal/api/osac/private/v1"
	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockExternalIPsClient is a mock of ExternalIPsClient interface.
type MockExternalIPsClient struct {
	ctrl     *gomock.Controller
	recorder *MockExternalIPsClientMockRecorder
	isgomock struct{}
}

// MockExternalIPsClientMockRecorder is the mock recorder for MockExternalIPsClient.
type MockExternalIPsClientMockRecorder struct {
	mock *MockExternalIPsClient
}

// NewMockExternalIPsClient creates a new mock instance.
func NewMockExternalIPsClient(ctrl *gomock.Controller) *MockExternalIPsClient {
	mock := &MockExternalIPsClient{ctrl: ctrl}
	mock.recorder = &MockExternalIPsClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExternalIPsClient) EXPECT() *MockExternalIPsClientMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockExternalIPsClient) Create(ctx context.Context, in *privatev1.ExternalIPsCreateRequest, opts ...grpc.CallOption) (*privatev1.ExternalIPsCreateResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Create", varargs...)
	ret0, _ := ret[0].(*privatev1.ExternalIPsCreateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockExternalIPsClientMockRecorder) Create(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockExternalIPsClient)(nil).Create), varargs...)
}

// Delete mocks base method.
func (m *MockExternalIPsClient) Delete(ctx context.Context, in *privatev1.ExternalIPsDeleteRequest, opts ...grpc.CallOption) (*privatev1.ExternalIPsDeleteResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Delete", varargs...)
	ret0, _ := ret[0].(*privatev1.ExternalIPsDeleteResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockExternalIPsClientMockRecorder) Delete(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockExternalIPsClient)(nil).Delete), varargs...)
}

// Get mocks base method.
func (m *MockExternalIPsClient) Get(ctx context.Context, in *privatev1.ExternalIPsGetRequest, opts ...grpc.CallOption) (*privatev1.ExternalIPsGetResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Get", varargs...)
	ret0, _ := ret[0].(*privatev1.ExternalIPsGetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockExternalIPsClientMockRecorder) Get(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockExternalIPsClient)(nil).Get), varargs...)
}

// List mocks base method.
func (m *MockExternalIPsClient) List(ctx context.Context, in *privatev1.ExternalIPsListRequest, opts ...grpc.CallOption) (*privatev1.ExternalIPsListResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "List", varargs...)
	ret0, _ := ret[0].(*privatev1.ExternalIPsListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockExternalIPsClientMockRecorder) List(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockExternalIPsClient)(nil).List), varargs...)
}

// Signal mocks base method.
func (m *MockExternalIPsClient) Signal(ctx context.Context, in *privatev1.ExternalIPsSignalRequest, opts ...grpc.CallOption) (*privatev1.ExternalIPsSignalResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Signal", varargs...)
	ret0, _ := ret[0].(*privatev1.ExternalIPsSignalResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Signal indicates an expected call of Signal.
func (mr *MockExternalIPsClientMockRecorder) Signal(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Signal", reflect.TypeOf((*MockExternalIPsClient)(nil).Signal), varargs...)
}

// Update mocks base method.
func (m *MockExternalIPsClient) Update(ctx context.Context, in *privatev1.ExternalIPsUpdateRequest, opts ...grpc.CallOption) (*privatev1.ExternalIPsUpdateResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Update", varargs...)
	ret0, _ := ret[0].(*privatev1.ExternalIPsUpdateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockExternalIPsClientMockRecorder) Update(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockExternalIPsClient)(nil).Update), varargs...)
}

// MockExternalIPsServer is a mock of ExternalIPsServer interface.
type MockExternalIPsServer struct {
	ctrl     *gomock.Controller
	recorder *MockExternalIPsServerMockRecorder
	isgomock struct{}
}

// MockExternalIPsServerMockRecorder is the mock recorder for MockExternalIPsServer.
type MockExternalIPsServerMockRecorder struct {
	mock *MockExternalIPsServer
}

// NewMockExternalIPsServer creates a new mock instance.
func NewMockExternalIPsServer(ctrl *gomock.Controller) *MockExternalIPsServer {
	mock := &MockExternalIPsServer{ctrl: ctrl}
	mock.recorder = &MockExternalIPsServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExternalIPsServer) EXPECT() *MockExternalIPsServerMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockExternalIPsServer) Create(arg0 context.Context, arg1 *privatev1.ExternalIPsCreateRequest) (*privatev1.ExternalIPsCreateResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(*privatev1.ExternalIPsCreateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockExternalIPsServerMockRecorder) Create(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockExternalIPsServer)(nil).Create), arg0, arg1)
}

// Delete mocks base method.
func (m *MockExternalIPsServer) Delete(arg0 context.Context, arg1 *privatev1.ExternalIPsDeleteRequest) (*privatev1.ExternalIPsDeleteResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(*privatev1.ExternalIPsDeleteResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockExternalIPsServerMockRecorder) Delete(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockExternalIPsServer)(nil).Delete), arg0, arg1)
}

// Get mocks base method.
func (m *MockExternalIPsServer) Get(arg0 context.Context, arg1 *privatev1.ExternalIPsGetRequest) (*privatev1.ExternalIPsGetResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(*privatev1.ExternalIPsGetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockExternalIPsServerMockRecorder) Get(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockExternalIPsServer)(nil).Get), arg0, arg1)
}

// List mocks base method.
func (m *MockExternalIPsServer) List(arg0 context.Context, arg1 *privatev1.ExternalIPsListRequest) (*privatev1.ExternalIPsListResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1)
	ret0, _ := ret[0].(*privatev1.ExternalIPsListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockExternalIPsServerMockRecorder) List(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockExternalIPsServer)(nil).List), arg0, arg1)
}

// Signal mocks base method.
func (m *MockExternalIPsServer) Signal(arg0 context.Context, arg1 *privatev1.ExternalIPsSignalRequest) (*privatev1.ExternalIPsSignalResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Signal", arg0, arg1)
	ret0, _ := ret[0].(*privatev1.ExternalIPsSignalResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Signal indicates an expected call of Signal.
func (mr *MockExternalIPsServerMockRecorder) Signal(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Signal", reflect.TypeOf((*MockExternalIPsServer)(nil).Signal), arg0, arg1)
}

// Update mocks base method.
func (m *MockExternalIPsServer) Update(arg0 context.Context, arg1 *privatev1.ExternalIPsUpdateRequest) (*privatev1.ExternalIPsUpdateResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(*privatev1.ExternalIPsUpdateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockExternalIPsServerMockRecorder) Update(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockExternalIPsServer)(nil).Update), arg0, arg1)
}

// mustEmbedUnimplementedExternalIPsServer mocks base method.
func (m *MockExternalIPsServer) mustEmbedUnimplementedExternalIPsServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedExternalIPsServer")
}

// mustEmbedUnimplementedExternalIPsServer indicates an expected call of mustEmbedUnimplementedExternalIPsServer.
func (mr *MockExternalIPsServerMockRecorder) mustEmbedUnimplementedExternalIPsServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedExternalIPsServer", reflect.TypeOf((*MockExternalIPsServer)(nil).mustEmbedUnimplementedExternalIPsServer))
}

// MockUnsafeExternalIPsServer is a mock of UnsafeExternalIPsServer interface.
type MockUnsafeExternalIPsServer struct {
	ctrl     *gomock.Controller
	recorder *MockUnsafeExternalIPsServerMockRecorder
	isgomock struct{}
}

// MockUnsafeExternalIPsServerMockRecorder is the mock recorder for MockUnsafeExternalIPsServer.
type MockUnsafeExternalIPsServerMockRecorder struct {
	mock *MockUnsafeExternalIPsServer
}

// NewMockUnsafeExternalIPsServer creates a new mock instance.
func NewMockUnsafeExternalIPsServer(ctrl *gomock.Controller) *MockUnsafeExternalIPsServer {
	mock := &MockUnsafeExternalIPsServer{ctrl: ctrl}
	mock.recorder = &MockUnsafeExternalIPsServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUnsafeExternalIPsServer) EXPECT() *MockUnsafeExternalIPsServerMockRecorder {
	return m.recorder
}

// mustEmbedUnimplementedExternalIPsServer mocks base method.
func (m *MockUnsafeExternalIPsServer) mustEmbedUnimplementedExternalIPsServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedExternalIPsServer")
}

// mustEmbedUnimplementedExternalIPsServer indicates an expected call of mustEmbedUnimplementedExternalIPsServer.
func (mr *MockUnsafeExternalIPsServerMockRecorder) mustEmbedUnimplementedExternalIPsServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedExternalIPsServer", reflect.TypeOf((*MockUnsafeExternalIPsServer)(nil).mustEmbedUnimplementedExternalIPsServer))
}
