---
name: Remove ok-to-test on new push
on:
  pull_request_target:
    types: [synchronize]

jobs:
  remove-label:
    permissions:
      pull-requests: write
    if: contains(github.event.pull_request.labels.*.name, 'ok-to-test')
    uses: osac-project/osac-test-infra/.github/workflows/ok-to-test-label-cleanup.yml@main
    secrets: inherit
